### ISSUE TITLE
https://github.com/carbonblack/binee/blob/master/windows/registry_test.go#L3

### ISSUE THREAD

**Issue by evandrix** [carbonblack/binee#16]
@knightsc made a blunder in this commit: https://github.com/carbonblack/binee/commit/5ef4646e7b7b845a56a307c806fbac48e26f532c#diff-1ab5230d2f4138b29ddfc19bc662d0b3

`import "github.com/carbonblack/ee/windows"` ... `/ee/` should be `/binee/`

**Comment by kgwinnup** [comment]
fixed issue. Thank you!
