### ISSUE TITLE
Install instructions may be missing a step or a config changed?

### ISSUE THREAD

**Issue by import-au** [carbonblack/binee#3]
I had to modify the GOPATH to get go get and go build to run based on the README instructions. 

> export GOPATH="/bineedev/go:/trml/go/"

**Comment by jholowczak-cb** [comment]
Hi,

The instructions for running the docker container in both the README and the wiki were out of date in reference to changes made in the dockerfile. I just pushed some updates to both, and this should be fixed now. Feel free to reopen if you run into any more issues.

**Comment by import-au** [comment]
Thanks for the quick response!
