### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by utkonos** [carbonblack/binee#62]
Panic on test binary:

```
# ./binee tests/ConsoleApplication1_x86.exe 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x54c0e2]

goroutine 1 [running]:
github.com/carbonblack/binee/windows.(*WinEmulator).initPe(0xc00014a480, 0xc00015e000, 0x7fffff46e763, 0x21, 0x4, 0x4, 0xc000120030, 0x0, 0x0, 0x0, ...)
	/root/binee-master/windows/loader.go:872 +0xdf2
github.com/carbonblack/binee/windows.LoadMem(0xc00015e000, 0x7fffff46e763, 0x21, 0xc000120030, 0x0, 0x0, 0xc000141ed0, 0x7fc2875e6d01, 0xc000128598, 0xc000141c50)
	/root/binee-master/windows/winemulator.go:340 +0x2249
github.com/carbonblack/binee/windows.Load(0x7fffff46e763, 0x21, 0xc000120030, 0x0, 0x0, 0xc000141ed0, 0xc000128598, 0xc0001123c0, 0xc000141ce8)
	/root/binee-master/windows/winemulator.go:169 +0xfd
main.main()
	/root/binee-master/main.go:133 +0xde0
```

Ubuntu environment:
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```

Unicorn engine 1.0.2-rc3 compiled like so:
```
apt install build-essential
wget https://github.com/unicorn-engine/unicorn/archive/1.0.2-rc3.tar.gz
tar -zxvf 1.0.2-rc3.tar.gz 
cd unicorn-1.0.2-rc3/
UNICORN_ARCHS="aarch64"
./make.sh
./make.sh install
echo "/usr/lib64" > /etc/ld.so.conf.d/unicorn.conf
ldconfig
./samples/sample_all.sh
```

binee installed like so:
```
apt install unzip
snap install --classic go
wget https://github.com/carbonblack/binee/archive/master.zip
unzip master.zip 
cd binee-master/
go build
mkdir os
cd os
mkdir win10_32
cd win10_32/
mkdir windows
cd windows/
mv ~/binee-master/system32 .
cd
cd binee-master/
./binee tests/ConsoleApplication1_x86.exe
```

**Comment by jholowczak** [comment]
Hi, thanks for submitting an issue. I'm going to spin up an Ubuntu VM and try to recreate. The system DLL location seems good, however just curious on where you collected the DLL's (system32) from to put in `os/win10_32/`. Thanks!

**Comment by utkonos** [comment]
It was a copy of a clean analysis VM's /Windows/System32 directory, with the files changed to lowercase filenames. The documentation mentions a one-liner and links to another place in the documentation, but that one-liner is missing from that location that was linked to. I just changed the DLL filenames from the errors until binee stopped throwing errors besides this one. Here is the version info:

![image](https://user-images.githubusercontent.com/2775739/79691292-a95f7a00-822c-11ea-8c70-a260f041e858.png)

**Comment by utkonos** [comment]
This windows VM is windows 10 x64 pro not x32. Is this a problem?

**Comment by jholowczak** [comment]
Ah yes, that would probably be a good chunk of the problem. 64-bit DLL's are currently incompatible, so they would need to be pulled from an x32 system. We're actively working on 64-bit support (you may already see some remnants of 64 bit stuff sprinkled throughout the code but it's not to the point of "stability" yet). I'll take a look at the documentation to fix any missing references.

**Comment by utkonos** [comment]
BTW: the windows install is from "Win10_1903_V1_English_x64.iso"

```
$ shasum -a 256 Win10_1903_V1_English_x64.iso
9846dfbdd7c39eb8d025e0f28e180c6f4084ecf87ecd11805cd19c205f7a3b4e  Win10_1903_V1_English_x64.iso
```

**Comment by utkonos** [comment]
Using 32-bit Windows almost everything works. The test file `tests/ConsoleApplication1_x64.exe` doesn't appear to run at all, and there is one invalid fetch on the file `tests/thread_test.exe`

```
[2] 0x20b23240: P __acrt_iob_func() = 0x403378
[3] 0x20b1e760: F __stdio_common_vfprintf(stream = 0x0, format = 'tid %d, count %d\n', p0 = 0x1, p1 = 0x2) = 0x403378
Invalid Fetch: addresss = 0x0, size = 0x1, value = 0x0
[2] 0x20b1e760: F __stdio_common_vfprintf(stream = 0x0, format = 'tid %d, count %d\n', p0 = 0x0, p1 = 0x3) = 0x403378
```

Lastly, at least one of these files requires C++ Redistributable. Therefore, that needs to be installed before copying the system32 directory to the mock filesystem.

**Comment by utkonos** [comment]
BTW: Here are the steps for Ubuntu 19.10

Use Windows 10 Pro 32-bit image:
https://www.microsoft.com/en-us/software-download/windows10ISO

Install Microsoft Visual C++ Redistributable:
https://aka.ms/vs/16/release/vc_redist.x86.exe

Mount storage at /mnt/win10x32_system32
Copy c:\Windows\System32 to /mnt/win10x32_system32/system32
Skip any files that won’t copy.

Run these in the VM:
```
cd /mnt/win10x32_system32/system32
for f in `find`; do mv -v "$f" "`echo $f | tr '[A-Z]' '[a-z]'`"; done
```

Install Unicorn Engine:
```
apt install build-essential
wget https://github.com/unicorn-engine/unicorn/archive/1.0.2-rc3.tar.gz
tar -zxvf 1.0.2-rc3.tar.gz
cd unicorn-1.0.2-rc3/
UNICORN_ARCHS="aarch64"
./make.sh
./make.sh install
echo "/usr/lib64" > /etc/ld.so.conf.d/unicorn.conf
ldconfig
./samples/sample_all.sh
```

Install binee:
```
apt install unzip
snap install --classic go
wget https://github.com/carbonblack/binee/archive/master.zip
unzip master.zip
cd binee-master/
mkdir -p os/win10_32/windows
cd os/win10_32/windows/
ln -s /mnt/win10x32_system32/system32/ .
cd ../../..
go build
./binee tests/ConsoleApplication1_x86.exe
```
