### ISSUE TITLE
Slack invite link in README is dead

### ISSUE THREAD

**Issue by evandrix** [carbonblack/binee#67]
i.e. https://join.slack.com/t/cb-binee/shared_invite/enQtODAwMjM5NzU4MDY4LTE3ZjJkY2FiNmIwMjExOTcwZDAxMjllZjdhODExNDZiZGFkOTJkZTU4YzY0YzVmMTc0N2ExMmYzMzg5MjNhOWU

can i get a new invite pls?

**Comment by jholowczak** [comment]
Hi,
I just updated the workspace invite link to something that should never expire. Thanks for pointing out the expiration!
